# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            FTACO.NET
tagline:          'A Jekyll theme'
description:      ''
url:              https://ftaco-net.github.io
baseurl:          /

author:
  name:           ''
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           

theme: jekyll-theme-minimal